app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as v

urlpatterns=[

    path('',views.indexPage,name='index'),
    path('register/',views.registerPage,name='register'),
    path('login/',views.login_page,name='login'),
    path('logout/',views.logout_user,name='logout'),
    path('menu/',views.menu,name='menu'),
    path('my_orders/',views.my_orders,name='my_orders'),
    path('add/<int:pk>',views.add_cart,name='add_cart'),
    path('del/<int:pk>',views.delete_cart,name='del'),
    path('plus/<int:pk>',views.plus_item,name='plus'),
    path('minus/<int:pk>',views.minus_item,name='minus'),
    path('my_account',views.my_account,name='my_account'),
    path('fil_category/<int:cat>/<int:canteen>',views.fil_category,name='fil_category'),
    path('my_order/',views.my_order,name='my_order'),

#for password change and reset purpose
    path('password-chang/',v.PasswordChangeView.as_view(template_name='app/password_change.html'),name='change_password'),
 
    path('password-change-done/', v.PasswordChangeDoneView.as_view(template_name='app/password_change_done.html'),name='password_change_done'),

    path('password-reset/', v.PasswordResetView.as_view(template_name='app/password_reset.html', email_template_name='app/password_reset_email.html',subject_template_name='app/password_reset_email_subject.txt'),name='password_reset'),
    path('password-reset-done/', v.PasswordResetDoneView.as_view(template_name='app/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>', v.PasswordResetConfirmView.as_view(template_name='app/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', v.PasswordResetCompleteView.as_view(template_name='app/password_reset_complete.html'), name='password_reset_complete'),
    path('details/<int:pk>',views.ingredients,name='ingredients'),
    path('add_rating',views.add_rating,name='add_rating'),
    path('home_search',views.home_search,name='home_search'),
    path('about_us',views.about_us,name='about_us'),
    path('back',views.back,name='back'),
    path('edit_profile/',views.edit_profile,name='user_edit'),

    #payment
    path('handlerequest/',views.handlerequest,name='handlerequest'),
    
    ]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    path('canteen/',include('app1.urls')),
    


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model
# AbstractBaseUser AbstractUser

class User(AbstractUser):
	
	is_staff=models.BooleanField(default=False)
	is_student=models.BooleanField(default=False)
	phone=models.BigIntegerField(default=91)
	is_restaurant=models.BooleanField(default=False)
	profile=models.ImageField(upload_to='profile/',default='pro.png')

	

	def __str__(self):
		return self.first_name+' '+self.last_name
	
		
class Customer(models.Model):
	customer=models.OneToOneField(get_user_model(),on_delete=models.CASCADE)
	college_id=models.BigIntegerField(default=10000)
	idImage=models.ImageField(null=True,blank=True)

	def __str__(self):
		return self.customer.first_name

class CanteenProfile(models.Model):
	canteen=models.OneToOneField(get_user_model(),on_delete=models.CASCADE)
	canteen_rating=models.CharField	(max_length=20,default='Not Assigned',choices=(('1','1'),('2','2'),('3','3'),('4','4'),('5','5')))
	status=models.CharField(max_length=20,default='Active',choices=(('Block','Block'),('Active','Active')))

  

app/templates/app/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>

    <!-- Basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0">

    
    <!-- Site Metas -->
    <title>Food Funday Restaurant - One page HTML Responsive</title>

    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon" />
    <link rel="apple-touch-icon" href="{% static 'images/apple-touch-icon.png' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- Site CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Responsive CSS -->
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <!-- color -->
    <link id="changeable-colors" rel="stylesheet" href="{% static 'css/colors/orange.css' %}" />

    <!-- Modernizer -->
    <script src="{% static 'js/modernizer.js' %}"></script>

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    
    <div id="loader">
        <div id="status"></div>
    </div>
    <div id="site-header">
        <header id="header" class="header-block-top">
            <div class="container">
                <div class="row">
                    <div class="main-menu">
                        <!-- navbar -->
                        <nav class="navbar navbar-default" id="mainNav">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                <div class="logo">
                                    <a class="navbar-brand js-scroll-trigger logo-header" href="#">
                                        <img src="{% static 'images/logo.png' %}" alt="">
                                    </a>
                                </div>
                            </div>
                            <div id="navbar" class="navbar-collapse collapse" style="background-color: black">
                                <ul class="nav navbar-nav navbar-right">
                                    <li class="active"><a href="{% url 'index' %}">Home</a></li>
                                    <li class="active"><a href="{% url 'about_us' %}">About us</a></li>
                                    <li class="active"><a href="{% url 'menu' %}">Menu</a></li>
                                    {% if user.is_authenticated %}
                                    <li class="active"><a href="{% url 'my_orders' %}">My Orders</a></li>
                                    <li class="active"><a href="{% url 'my_account' %}">My Account</a></li>
                                    <li class="active"><a href="{% url 'logout' %}">Logout</a></li>

                                    {% else %}
                                    
                                    <li class="active"><a href="{% url 'login' %}">Login</a></li>
                                    <li class="active"><a href="{% url 'register' %}">register</a></li> 
                                    
                                    <li class="active"><a href="#footer">Contact us</a></li>
                                    {% endif %}
                                </ul>
                            </div>
                            <!-- end nav-collapse -->
                        </nav>
                        <!-- end navbar -->
                    </div>
                </div>
                <!-- end row -->
            </div>
            <!-- end container-fluid -->
        </header>
        <!-- end header -->
    </div>
	<!-- end site-header -->

    {% block content %}
    {% endblock %}

    <div id="footer" class="footer-main">
        <div class="footer-box pad-top-70">
            <div class="container">
                <div class="row">
                    <div class="footer-in-main">
                        <div class="footer-logo">
                            <div class="text-center">
                                <img src="{% static 'images/logo.png' %}" alt="" />
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                            <div class="footer-box-a">
                                <h3>About Us</h3>
                                <p>We are final year students pursuing B.E specialized in I.T, and this is our final year project. We are working on this using Python+Django.</p>
                                <ul class="socials-box footer-socials pull-left">
                                    <li>
                                        <a href="#">
                                            <div class="social-circle-border"><i class="fa  fa-facebook"></i></div>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <div class="social-circle-border"><i class="fa fa-twitter"></i></div>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <div class="social-circle-border"><i class="fa fa-google-plus"></i></div>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <div class="social-circle-border"><i class="fa fa-pinterest"></i></div>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <div class="social-circle-border"><i class="fa fa-linkedin"></i></div>
                                        </a>
                                    </li>
                                </ul>

                            </div>
                            <!-- end footer-box-a -->
                        </div>
                        <!-- end col -->
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                            <div class="footer-box-b">
                                <h3>New Menu</h3>
                                <ul>
                                    <li><a href="#">Italian Bombay Sandwich</a></li>
                                    <li><a href="#">Cheese Masala Dosa</a></li>
                                    <li><a href="#">French Fries</a></li>
                                    <li><a href="#">Italian Pizza</a></li>
                                    <li><a href="#">Capacino</a></li>
                                </ul>
                            </div>
                            <!-- end footer-box-b -->
                        </div>
                        <!-- end col -->
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                            <div class="footer-box-c">
                                <h3>Contact Us</h3>
                                <p>
                                    <i class="fa fa-map-signs" aria-hidden="true"></i>
                                    <span>SVMIT
                                        Old, NH 48, Bharuch, Gujarat,392001
                                     </span>
                                </p>
                                <p>
                                    <i class="fa fa-mobile" aria-hidden="true"></i>
                                    <span>
                                    +91 9924883676
                                    +91 8511377799
                                    +91 7621813478
                                </span>
                                </p>
                                <p>
                                    <i class="fa fa-envelope" aria-hidden="true"></i>
                                    <span><a href="#">support@foodfunday.com</a></span>
                                </p>
                            </div>
                            <!-- end footer-box-c -->
                        </div>
                        <!-- end col -->
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                            <div class="footer-box-d">
                                <h3>Opening Hours</h3>

                                <ul>
                                    <li>
                                        <p>Monday - Saturday </p>
                                        <span> 8:00 AM - 11:00 PM</span>
                                    </li>
                                    <li>
                                        <p>Sunday </p>
                                        <span>11:00 AM - 5:00 PM</span>
                                    </li>
                                </ul>
                            </div>
                            <!-- end footer-box-d -->
                        </div>
                        <!-- end col -->
                    </div>
                    <!-- end footer-in-main -->
                </div>
                <!-- end row -->
            </div>
            <!-- end container -->
            <div id="copyright" class="copyright-main">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <h6 class="copy-title"> Copyright &copy; 2017 Food Funday is powered by <a href="#" target="_blank"></a> </h6>
                        </div>
                    </div>
                    <!-- end row -->
                </div>
                <!-- end container -->
            </div>
            <!-- end copyright-main -->
        </div>
        <!-- end footer-box -->
    </div>
    <!-- end footer-main -->

    <a href="#" class="scrollup" style="display: none;">Scroll</a>

    
    <!-- ALL JS FILES -->
    <script src="{% static 'js/all.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- ALL PLUGINS -->
    <script src="{% static 'js/custom.js' %}"></script>

    
</body>

</html>

app/templates/app/confirm_order.html
{% extends 'app/base.html' %}
{% block content %}

{{user.first_name}}{{user.last_name}} you have ordered the below food item:

{% endblock %}

app/templates/app/edit_profile.html
{% extends 'app\base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}


<style>
     #hint_id_username {
         display: none;
     }

</style>
<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script type="text/javascript">
     $(document).ready(function(){
     		$('#id_phone').attr('readonly', true);
     		$('#id_email').attr('readonly', true); 

     	});

</script>


<div class="container" style="padding-top: 10%">
    <div class="row" >
    		<div class="col-md-3" >
    		</div>
      
            <div class="col-md-6" >
            	<br>
            	<b><H1> Edit Profile</H1></b>

            <form method="POST">

                  {% csrf_token %}
                  {{form2|crispy}}
                  {{form|crispy}}
                  <button type="submit" class="btn btn-success">Edit Profile</button>
            </form>
       
</div>
</div>
</div></div>

<br>
{% endblock %}

app/templates/app/login.html
{% extends 'app/base.html' %}

{% block content %}
<div class="container">
	<div class="row" >
		<div class="col-4" >

<form method="post" style="padding-top: 15%;padding: 20%;" >
	{% csrf_token %}
  <I><h1 style="text-align: center;font-size: 7;"><B><FONT SIZE="7" FACE="nautilus_pompiliusregular"> Customer Login</FONT></B></h1></I><br>
	<div class="form-group">
    <label for="exampleInputEmail1">Phone Number</label>
    <input type="number" name='phone' class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Phone number">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" name='password' class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label><br>
    
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
  <br>
  <a href="{% url 'password_reset' %}">Forgot Password....??</a><br>
  <div style="color:red">{{message}}</div>
</form>
</div></div>
</div>

{% endblock %}

app/templates/app/my_orders.html
{% extends 'app/base.html' %}

{% block content %}

<style>

.rating {
  display: inline-block;
  position: relative;
  height: 30px;
  line-height: 20px;
  font-size: 20px;
}

.rating label {
  position: absolute;
  top: 0;
  left: 0;
  height: 40%;
  cursor: pointer;
}

.rating label:last-child {
  position: static;
}

.rating label:nth-child(1) {
  z-index: 5;
}

.rating label:nth-child(2) {
  z-index: 4;
}

.rating label:nth-child(3) {
  z-index: 3;
}

.rating label:nth-child(4) {
  z-index: 2;
}

.rating label:nth-child(5) {
  z-index: 1;
}

.rating label input {
  position: absolute;
  top: 0;
  left: 0;
  opacity: 0;
}

.rating label .icon {
  float: left;
  color: transparent;
}

.rating label:last-child .icon {
  color: #000;
}

.rating:not(:hover) label input:checked ~ .icon,
.rating:hover label:hover input ~ .icon {
  color:orange;
}

.rating label input:focus:not(:checked) ~ .icon:last-child {
  color: #000;
  text-shadow: 0 0 5px #09f;
}
</style>
<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>

<script>
$(document).ready(function(){
    $(':radio').change(function() {
        var v = $(this).closest("form").find("input[type='hidden']").val();
        console.log(v);
        $.ajax({
            url:"{% url 'add_rating' %}",
            data:{
                'rate':this.value,
                'food':v
                
            },
            success: function (data) {
                
            }
        })
  console.log('New star rating: ' + this.value);
});


})



</script>

<div class="container" style="padding-top: 15%;">
	<div class="row" >
		<div class="col-4" >
{% for i in order %}
<h1 style="font-size:xx-large;color: darkred;text-align: center;font-family:inherit;"> <b>Your Reciept</b> </h1><br>

<div style="border-style:dashed;border-color: purple; padding:20px;font-size: large;font-family:Verdana, Geneva, Tahoma, sans-serif; color:orangered;">
   <b><span style="color:darkgreen;"> Order ID: </span></b>  {{i.id}} <br>
   <b><span style="color:darkgreen;"> Canteen Name:</span> </b> {{i.ordered_to.first_name|title}}<br>
   <b><span style="color:darkgreen;">Transaction id:</span> </b>{{i.transaction_id}}<br>


   {% for j in item %}
   {% if i == j.order_id %}
  <b> <span style="color:darkgreen;">Food Item:</span></b> {{j.menu.food_name}}<br>
       <!-- {{j.menu.price}} -->
       
      <b><span style="color:darkgreen;"> Quantity:</span></b> {{j.quant}}<br>

   <b><span style="color:darkgreen;"> Ordered Time:</span></b> {{i.ordered_at}}<br>
   <b><span style="color:darkgreen;">Serving Time:</span></b> {{i.time}}<br>
   <b><span style="color:darkgreen;">Canteen Status:</span> </b>{{i.status}}<br>
   <b><span style="color:darkgreen;">Total Price:</span></b> {{i.total_price}}<br>
   
    <!-- <table>
        <tr> <td> Item Name</td>
            <td> Price</td><br>
            <td> Quantity</td><br></tr> -->
             
     
            <td> <b><span style="color:darkgreen;"> Add Rating:</span></b></td></tr>


            <td><form class="rating">
              <label>
                  <input type="hidden" id="{{j.id}}" value="{{j.id}}">
                  {% if j.cust_rating == 0 %}
                <input type="radio" name="stars" value="1" />
                <span class="icon">★</span>
              </label>
              <label>
                <input type="radio" name="stars" value="2" />
                <span class="icon">★</span>
                <span class="icon">★</span>
              </label>
              <label>
                <input type="radio" name="stars" value="3" />
                <span class="icon">★</span>
                <span class="icon">★</span>
                <span class="icon">★</span>   
              </label>
              <label>
                <input type="radio" name="stars" value="4" />
                <span class="icon">★</span>
                <span class="icon">★</span>
                <span class="icon">★</span>
                <span class="icon">★</span>
              </label>
              <label>
                <input type="radio" name="stars" value="5" />
                <span class="icon">★</span>
                <span class="icon">★</span>
                <span class="icon">★</span>
                <span class="icon">★</span>
                <span class="icon">★</span>
              </label>
              {% endif %}
              <br>

              
              {% if j.cust_rating == 1 %}
              <input type="radio" name="stars" value="1" style="color: orange;"  checked/>
              <span class="icon">★</span>
            </label>
            <label>
              <input type="radio" name="stars" value="2" style="color: orange;" />
              <span class="icon">★</span>
              <span class="icon">★</span>
            </label>
            <label>
              <input type="radio" name="stars" value="3" style="color: orange;"  />
              <span class="icon">★</span>
              <span class="icon">★</span>
              <span class="icon">★</span>   
            </label>
            <label>
              <input type="radio" name="stars" value="4"  />
              <span class="icon">★</span>
              <span class="icon">★</span>
              <span class="icon">★</span>
              <span class="icon">★</span>
            </label>
            <label>
              <input type="radio" name="stars" value="5"  />
              <span class="icon">★</span>
              <span class="icon">★</span>
              <span class="icon">★</span>
              <span class="icon">★</span>
              <span class="icon">★</span>
            </label>
              {% endif %}


              
              {% if j.cust_rating == 2 %}
              <input type="radio" name="stars" value="1"  />
              <span class="icon">★</span>
            </label>
            <label>
              <input type="radio" name="stars" value="2" checked/>
              <span class="icon">★</span>
              <span class="icon">★</span>
            </label>
            <label>
              <input type="radio" name="stars" value="3"   />
              <span class="icon">★</span>
              <span class="icon">★</span>
              <span class="icon">★</span>   
            </label>
            <label>
              <input type="radio" name="stars" value="4"  />
              <span class="icon">★</span>
              <span class="icon">★</span>
              <span class="icon">★</span>
              <span class="icon">★</span>
            </label>
            <label>
              <input type="radio" name="stars" value="5"  />
              <span class="icon">★</span>
              <span class="icon">★</span>
              <span class="icon">★</span>
              <span class="icon">★</span>
              <span class="icon">★</span>
            </label>
              {% endif %}

              
              {% if j.cust_rating == 3 %}
              <input type="radio" name="stars" value="1"/>
              <span class="icon">★</span>
            </label>
            <label>
              <input type="radio" name="stars" value="2" />
              <span class="icon">★</span>
              <span class="icon">★</span>
            </label>
            <label>
              <input type="radio" name="stars" value="3" checked  />
              <span class="icon">★</span>
              <span class="icon">★</span>
              <span class="icon">★</span>   
            </label>
            <label>
              <input type="radio" name="stars" value="4"  />
              <span class="icon">★</span>
              <span class="icon">★</span>
              <span class="icon">★</span>
              <span class="icon">★</span>
            </label>
            <label>
              <input type="radio" name="stars" value="5"  />
              <span class="icon">★</span>
              <span class="icon">★</span>
              <span class="icon">★</span>
              <span class="icon">★</span>
              <span class="icon">★</span>
            </label>
              {% endif %}


              {% if j.cust_rating == 4 %}
              <input type="radio" name="stars" value="1" style="color: orange;" />
              <span class="icon">★</span>
            </label>
            <label>
              <input type="radio" name="stars" value="2" style="color: orange;" />
              <span class="icon">★</span>
              <span class="icon">★</span>
            </label>
            <label>
              <input type="radio" name="stars" value="3" style="color: orange;"  />
              <span class="icon">★</span>
              <span class="icon">★</span>
              <span class="icon">★</span>   
            </label>
            <label>
              <input type="radio" name="stars" value="4" checked />
              <span class="icon">★</span>
              <span class="icon">★</span>
              <span class="icon">★</span>
              <span class="icon">★</span>
            </label>
            <label>
              <input type="radio" name="stars" value="5" />
              <span class="icon">★</span>
              <span class="icon">★</span>
              <span class="icon">★</span>
              <span class="icon">★</span>
              <span class="icon">★</span>
            </label>
              {% endif %}


              {% if j.cust_rating == 5 %}
              <input type="radio" name="stars" value="1" style="color: orange;" />
              <span class="icon">★</span>
            </label>
            <label>
              <input type="radio" name="stars" value="2" style="color: orange;" />
              <span class="icon">★</span>
              <span class="icon">★</span>
            </label>
            <label>
              <input type="radio" name="stars" value="3" style="color: orange;"  />
              <span class="icon">★</span>
              <span class="icon">★</span>
              <span class="icon">★</span>   
            </label>
            <label>
              <input type="radio" name="stars" value="4"  />
              <span class="icon">★</span>
              <span class="icon">★</span>
              <span class="icon">★</span>
              <span class="icon">★</span>
            </label>
            <label>
              <input type="radio" name="stars" value="5" checked />
              <span class="icon">★</span>
              <span class="icon">★</span>
              <span class="icon">★</span>
              <span class="icon">★</span>
              <span class="icon">★</span>
            </label>
              {% endif %}

          
          </form>    </td>
          </tr>
          <br>
          {% endif %}
          
          {% endfor %}   
        
            
        </div>
        <br><br>
{% endfor %}

</div>
</div>
</div>


{% endblock %}

app/templates/app/no_items.html
<div
<h1>No items found</h1>

app/templates/app/password_change.html
{% extends 'app/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container" style="padding-top: 10%;">
    <div class="row" >
    		<div class="col-md-3">
    		</div>
            <div class="col-md-6 offset-md-3" >
                
<form method='post'>
{% csrf_token %}
{{form|crispy}}
<input type="submit">
</form>
</div>
</div><br>
</div>

{% endblock %}

app/templates/app/password_change_done.html
{% extends 'app/base.html' %}
{% block content %}
<div class="container" style="padding-top: 10%;">
    <div class="row" >
            <div class="col-md-6" >
Password changed successfully

</div>
</div>
</div>


{% endblock %}

app/templates/app/password_reset_complete.html
{% extends 'app/base.html' %}
{% block content %}


Successfully Change Your Password

{% endblock %}

app/templates/app/password_reset_confirm.html
{% extends 'app/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div style="padding-top: 20%;align-self: center;">
  
{% if validlink %}
                    <form method="post" novalidate>
                        <h3 class="text-center">Change Your Password</h3>
                        {% csrf_token %}
                        {{form|crispy}}
                        <button type="submit" class="btn btn-success btn-block ">Change Password</button>
                    </form>
                {% else %}
                    <div class="alert alert-danger"  role="alert">
                        This link is already verified or invalid link
                    </div>
                        <a href="{% url 'password_reset' %}" class="text-center btn-block">Reset your Password</a>
                {% endif %}
{% endblock %}

app/templates/app/password_reset_email.html
Hii {{user.username}}
------------------------------------------------------------------------
To reset your password for Food Funday, please click on the following link below:

{{protocol}}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}


If you don't want to reset your password, you can ignore this message.


-------------------------------------------------------------------------------
Thank You !!!!
Team Food Funday....!!
Have a tasty day...!!!

                                        Please don't send request

app/templates/app/payment_status.html
{% extends 'app\base.html' %}

{% load static %}
{% block content %}

<div class="container" style="padding-top:10%">
   
    <div class="col my-4">
 
        <h2>Payment status regarding your order Id {{response.ORDERID}}</h2>
        {% if response.RESPCODE == '01' %}
        Order Placed Successfully<br>
        <h3>Amount Paid: {{response.TXNAMOUNT}}<br></hh3>
        <h3>Transaction id: {{response.TXNID}}</h3>
        {% else %}
        Order Failed. Please try again
        {% endif%}
 
    </div>
 
</div>

{% endblock %}